services:
  db:
    container_name: ${APP_NAME}-db
    image: postgres:16-alpine3.18
    restart: unless-stopped
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
        interval: 3s
        timeout: 3s
        retries: 10
    environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        PGDATA: /data/postgres
    ports:
        - ${DB_PORT}:5432
    volumes:
        - database:/data/postgres

  redis:
    image: redis:latest
    container_name: ${APP_NAME}-redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
    restart: always

volumes:
    database:
    redis-data:
        driver: local
